services:
  _defaults:
    public: false
    autowire: true

  PowerCaptcha\OxidEshop\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry
    public: true

  PowerCaptcha\OxidEshop\Service\ModuleSettingsInterface:
    class: PowerCaptcha\OxidEshop\Service\ModuleSettings
    public: true

  PowerCaptcha\OxidEshop\Service\TokenVerificationInterface:
    class: PowerCaptcha\OxidEshop\Service\TokenVerification
    public: true
